### ISSUE TITLE
Some titles get stuck at splash screen

### ISSUE THREAD

**Issue by AaronLayton** [wiiu-env/Tiramisu#1]
Not sure if you accepting issues here but figure this may be the best way to let you know :-)

I have just installed from virgin -> tiramisu and copied over some game backups. Some games work fine whilst others crash the system our at the game splash screens. The music is still playing but besides that the consoles become unresponsive and require a hard reboot.

Not sure how to provide any other information but will keep an eye on the issue if you need anything from me

Great work to both of you

**Comment by Kojinesman344** [comment]
I'm having trouble running VWII from Tiramisu Environment. I thought my VWII was corrupt and I proceeded to install thru VWII nand restorer a backup I had. The problem persist after a clean install and backup. Afterwards I might uninstall Tiramisu and just use Mocha if the problem persist.

**Comment by takoyaki99** [comment]
Have you tried booting from HBL2HBC?

**Comment by Kojinesman344** [comment]
It boots back to the wii u menu. I tried decaffeinator and vwii nand restorer to try to unbRick the part of the vwii boot load up but still trying to load HBC2HBL doesn't work and loading from startup the vwii to play games doesn't boot as well. I tried to boot VWII from Tiramisu Environment and still it doesn't work. The wii u hangs up music playing but no display and returns to wii u menu.

**Comment by takoyaki99** [comment]
My HBC2HBL didn’t work before, it depends on your HBC title ID. If it’s installed with compat_installer it’s OHBC and if it’s with Wuphax I think it’s LULZ.

My tiramisu booting (to HBC) doesn’t work too for some reason, probably for title ID reasons.

Have you tried using SysUpdate from decaffeinator, instead of NAND restoring?

**Comment by Kojinesman344** [comment]
Did the same for updating thru the decaf but while on Tiramisu Environment,the progress gets wonky. The update work after I unistalled the first time desperately trying to get it to work but I suspect that trying to work under Tiramisu might be the culprit. I'm going to unistalled tiramisu again and do the whole process with Haxchi to see if I get a different result.

**Comment by Maschell** [comment]
Tiramisu has been updated a few ago that should address the crashes when booting certain games. Please make sure to download the latest Tiramisu version.

Regarding the HBC issues maybe @GaryOderNichts can help

**Comment by Kojinesman344** [comment]
I might contact Gary if possible. But I'm going to try resolving with what I have and if I can't continue then I'll contact Gary.

**Comment by takoyaki99** [comment]
Is updating just replacing the files or do I need to go through the installation process again?

**Comment by Maschell** [comment]
It's enough to just replace the files on the sd card.  Click [here](https://tiramisu.foryour.cafe/package/tiramisu) on "Download All" an extract the content to the sd card, override any existing files

@Kojinesman344 It seems like the AutobootModule expects FIX' fork of the Homebrew Channel (https://github.com/FIX94/hbc/releases) as it fixes the aspect ratio of the screen and some other bugs which has a different title id?. It's might worth looking into a fallback for the "original" hbc though. Can you create a separate issue on the [AutobootModule](https://github.com/wiiu-env/AutobootModule) repo?

**Comment by Kojinesman344** [comment]
@Maschell  I'm going to try a clean install again and the other method as well to see if I get vwii to work again.

**Comment by upya4ko** [comment]
> It's enough to just replace the files on the sd card. Click [here](https://tiramisu.foryour.cafe/package/tiramisu) on "Download All" an extract the content to the sd card, override any existing files

Thanks !!!
Confirm,  have same problem "freeze at boot screen", updating [this](https://tiramisu.foryour.cafe/package/tiramisu)  ^^ files  fix problem.

**Comment by Maschell** [comment]
The issue seems resolved for now. If it's still persists feel to open a new issue.
