### ISSUE TITLE
5.5.6 Block

### ISSUE THREAD

**Issue by TheAvacad0** [wiiu-env/Tiramisu#26]
In 5.5.6 U Boot Patches somehow become blocked and the only way to activate them is via browser. This also means I can’t upgrade to aroma.

Region: USA
Version: 5.5.6 U

**Comment by Maschell** [comment]
What do you mean with "boot patches"?

**Comment by TheAvacad0** [comment]
I mean the cfw environment being activated on boot

**Comment by Maschell** [comment]
Why does it mean you can'u upgrade to Aroma? To upgrade to Aroma you just have to put the files on the sd card.
What happens when you hold X while booting?

**Comment by TheAvacad0** [comment]
Update: I just had to change my boot settings!
Aroma will hang my console though, might just wait until it’s stable

**Comment by Maschell** [comment]
> Aroma will hang my console though, might just wait until it’s stable

Aroma is more stable than Tiramisu. If booting into Aroma hangs, then you either have broken or missing files on the sd card. Please update the EnvironmentLoader and redownload Aroma
