### ISSUE TITLE
Mass Effect 3 hangs before start screen

### ISSUE THREAD

**Issue by SmirksAlot** [wiiu-env/Tiramisu#3]
With SD card inserted and Tiramisu autobooting from it, Mass Effect 3 won't finish loading to present start screen (shows the planet in space) this results in Wii U having to be hard reset. This behavior is the same for both the retail disc and a USB backup.

With the SD card removed from Wii U and Tiramisu not loaded, Mass Effect 3 loads from retail disc and USB with no issues.

Reproduced behavior with and without Bloopair loaded with latest Tiramisu files from today Jan 9 2022

**Comment by Cqtuanptit** [comment]
i have same problem

**Comment by Maschell** [comment]
I'll try to look into it, Mass Effect always has caused issues with homebrew. Until there is a fix you can boot the console with any hacks (hold R while booting) when you want to play this game

**Comment by Maschell** [comment]
Please download the latest version of Tiramisu here:
https://tiramisu.foryour.cafe/package/tiramisu (Click on "Download All" and copy the files to your sd card)

It should be fixed now.

**Comment by SmirksAlot** [comment]
I can confirm the issue is now resolved. thank you and i'll close this.
